### ISSUE TITLE
walkablewater breaks if theres a water gem in the level

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1000]
simply just remove water gems if walkable water is on (ALSOO WOOOOOOOOO 1000TH ISSUE YIPPEE)

https://github.com/user-attachments/assets/0dd39b4a-d57b-468e-abaf-3b9b7f0fce2e

**Comment by Bear64DX** [comment]
Wouldn't the `walkableWater` argument go *after* the pipes and springs? Idk might just be me lol

**Comment by EmeraldLoc** [comment]
What? `walkableWater` is ignored if Water is turned on. So if you enable water, gems exist, otherwise are removed. If a user changes the setting midway, and the water level has been raised or lowered. the only way to resolve that would be reloading the level, but that sounds unpleasant, so the user can just wait till next round for it to be resolved.
