### ISSUE TITLE
New levels - Bitdw and Bits

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1057]
I really dont see the problem in them, especially since theres levels exactly like them in tag.

**Comment by EmeraldLoc** [comment]
> especially since theres levels exactly like them in tag

Like?

**Comment by TheMan6900** [comment]
colorful blocks, mad musical mess, and even a level Im making called "underground void" (theres definitely way more than that)

**Comment by EmeraldLoc** [comment]
Oh no. Bitdw and Bits are linear, those levels aren't. As I've stated multiple times when reviewing y'alls romhacks, I've already expressed my meh view to linear levels. I let it slide in hacks (i.e that linear cotmc ripoff) because those generally have less stages, and im not as strict on those as I am in say, vanilla. I don't like linear levels, and vanilla is the one thing where I only want good stages, and I don't think bitdw and bits are gonna cut it (before you mention bitfs, I already wanted to cut that level, but when I asked people did NOT want it gone).

**Comment by Bear64DX** [comment]
> Oh no. Bitdw and Bits are linear, those levels aren't. As I've stated multiple times when reviewing y'alls romhacks, I've already expressed my meh view to linear levels. I let it slide in hacks (i.e that linear cotmc ripoff) because those generally have less stages, and im not as strict on those as I am in say, vanilla. I don't like linear levels, and vanilla is the one thing where I only want good stages, and I don't think bitdw and bits are gonna cut it (before you mention bitfs, I already wanted to cut that level, but when I asked people did NOT want it gone).

Hey, that cotmc "rip off" in Eureka is NOT a rip off. It's COTMC done RIGHT!! (also colorful blocks is mid lol)
