### ISSUE TITLE
Voting can randomly have 1 extra vote for a random level, before the voting starts

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1224]
weird

**Comment by EmeraldLoc** [comment]
This is gonna be a desync

**Comment by TheMan6900** [comment]
cant the game know that it has an unwanted vote?

**Comment by EmeraldLoc** [comment]
It can't do that reliably because what if your round state is desynced? What if your round timer is desynced? There's more factors then just that.

**Comment by TheMan6900** [comment]
How is level desynced able to be fixed, yet literally every other type of desync is unfixable?

**Comment by EmeraldLoc** [comment]
With a level desync, many factors are at play to ensure an invalid sync doesn't happen. First, there IS a reasonable way to detect a level desync, by seeing if your level is the same as the server's. If it's not, then a packet it sent to the server, asking "hey, I'm desynced, can you send me an ok to resync to your level?" The server receives this packet, goes "yea hold up let me hook you up," and sends their level to the client, and the client syncs their level with what the server got. There's only a few ways to track if the round state is desynced, and all of them aren't reliable, although I dont really want to go thru each one here. I'll explain how a desync checker would work for this.

On the clients end, their vote is nothing, so we only need to look at other players. So let's say a player looks at all other players voting indexes, and their round state is set to ROUND_WAIT. Now lets say one player's voting number isn't 0 (nothing), and is say 3. Ok! They're desynced! Now how can we initiate a resync without messing up everyone's else sync? Think about it, if your round state was desynced and you never entered the ROUND_VOTING state, now you see this player with an invalid voting number, and all the sudden nobody can vote. Ok, so we need to first check if your round state is desynced, but as stated above, this simply isn't reliable. A good way to check this for the voting round state would be to check if the servers voting number isn't 0, however because this can be desynced that isn't reliable anymore, ya see? The only way to fix it would be to send packets constantly, which is not ideal at all.

**Comment by TheMan6900** [comment]
A random idea I just got about desync: Is there any possible way to detect if a player that another player is trying to pvp, is desynced?

**Comment by EmeraldLoc** [comment]
The only way this would work is using the attacker index instead of the victim, however the way that triggers is different so it doesn't really work since it'll say you hit a player when in reality you didn't.

**Comment by TheMan6900** [comment]
What about the other way around? Having the game detect if you got hit but didn't actually get pvp'd
