### ISSUE TITLE
Spectate Toggle Bind

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1251]
Maybe X or Y. Would also have the toggle spectate text be changed to "Toggle Spectate (X/Y)" to also teach the player this. Would be a really nice qol.

**Comment by EmeraldLoc** [comment]
This can easily be accidentally toggled

**Comment by TheMan6900** [comment]
Wait how could this even be toggled by accident? The Y and X buttons are pretty clearly destined from the A B and other normal sm64 buttons, and even if you did toggle it on, you could very easily just toggle it off.

**Comment by EmeraldLoc** [comment]
> Wait how could this even be toggled by accident?

Good question, I wasn't thinking about it too clearly then, I believed you could become a spectator mid game for some reason, mb. Either way I do believe that theres already a lot of binds, and having another (useless) bind added on top of it because you can't pause the game hit down twice and hit A within a fraction of a second feels pretty useless and a waste of energy and more confusion.
