### ISSUE TITLE
Name inconsistency

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1265]
This is the level  'Boulder Rush" yet it has the name of reds in hmc?
![image](https://github.com/user-attachments/assets/1ac94e6d-169e-4daa-b6de-e2d8f5bc0639)

**Comment by Bear64DX** [comment]
Hazy Reds in the Cavern when emerald

**Comment by EmeraldLoc** [comment]
Is this during a match or during free roam?

**Comment by TheMan6900** [comment]
Both, I'm pretty sure this is something similar to the level swap glitch.

**Comment by EmeraldLoc** [comment]
Unrelated to level swap, believe I know the problem. When searching for the level, Red's in HMC is the first level with the level id `LEVEL_HMC`, so that name is picked. An easy fix is simply checking Mario's room. For a more permanent fix, for levels with blocks and what not, if you are in a match, simply pick the current level name in the `levels` table, otherwise, pick the default level name.

**Comment by TheMan6900** [comment]
this applies to every level that is segemented.

**Comment by EmeraldLoc** [comment]
Resolved

**Comment by EmeraldLoc** [comment]
> Hazy Reds in the Cavern when emerald

Ya know what ima go for this name, reds in the cavern isn't that bad
