### ISSUE TITLE
Stats wont load correctly when looked at decently quickly

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1286]
spammed stat page
![image](https://github.com/user-attachments/assets/24310c44-babc-44de-afd5-188efa04e415)

normal stat page
![image](https://github.com/user-attachments/assets/6f44708d-37be-47c0-818c-31d585b6275b)

**Comment by TheMan6900** [comment]
The intro message can also have a little hiccup when loading peoples stats (theres supposed to be a tagger stat here in the image but there simply isnt)
![image](https://github.com/user-attachments/assets/f6cb7e1f-b7b4-46a5-bd92-fc43b7603667)

**Comment by EmeraldLoc** [comment]
> The intro message can also have a little hiccup when loading peoples stats (theres supposed to be a tagger stat here in the image but there simply isnt)

Packet loss

> stats wont load correctly when spammed

Why the heck are you spamming it in the first place, just resolving bugs that shouldn't happen in the first place.

Anyways, were you spamming on multiple players names or just one?

**Comment by TheMan6900** [comment]
just one

**Comment by TheMan6900** [comment]
also is packet loss fixable?

**Comment by EmeraldLoc** [comment]
> also is packet loss fixable?

No it happens when someone has bad internet, sender or receiver

**Comment by TheMan6900** [comment]
> > also is packet loss fixable?
> 
> No it happens when someone has bad internet, sender or receiver

oh

**Comment by EmeraldLoc** [comment]
Gonna attribute this to packets being lost. The main issue is you're spamming a player with a bunch of packets that shouldn't be spammed, and the player is sending more requests then they should. Within my code I do not believe anything is wrong, and I can slightly confirm that with the fact this only happens if you spam it. If this happens when you casually request stats, that's one thing, if it happens when you are spamming a client with bad internet (as it has been established since the tagger message did not send), well I dont think that's reliable enough. The packet being sent it a rather large one compared to a normal packet size in coop, so.

**Comment by TheMan6900** [comment]
why cant say, another packet be sent if theres 10 - 20 seconds that the player stat page isnt being loaded?

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
uh like, if someones stats arent showing up, a basically refresh (or packet resent) would take place, giving the stat page another chance to show up correctly.
