### ISSUE TITLE
Make boosting while squished actually make you move faster

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1369]
pretty self explanatory.

**Comment by EmeraldLoc** [comment]
Are you sure it doesn't make you move faster, or is it just so small because you're already going so slow? Either way this is extremely nitpicky and won't actually affect the game. Based off of my code, it is technically increasing Marios speed, however maybe its not noticeable, like how its not noticeable in the walking action, when indeed it is happening
