### ISSUE TITLE
New joinned players as a round is ending join as a runner

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1407]
It just looks weird on the player menu

**Comment by EmeraldLoc** [comment]
This is intended

**Comment by TheMan6900** [comment]
why?

**Comment by EmeraldLoc** [comment]
Well first answer this question, why not? Because it looks weird on a specific item? What do you want it to say? Something misleading that isn't their actual role?

It's coded to have a new player join as a runner assuming the round state isn't set to active. The reason behind this is because that's how I coded it, reason being I wouldn't have to add unnecessary code like not setting Marios model state depending on the round state and other stuff like that, not including factoring in auto mode. Setting the default state to runner avoids a lot of excess code.
