### ISSUE TITLE
Make bullets poof/burst on contact with a player

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1422]
would just make the screen less cluttered, also would feel more natural

**Comment by EmeraldLoc** [comment]
Didn't you already make an issue on this (see https://github.com/EmeraldLoc/tag/issues/990)? I believe I did this.

**Comment by TheMan6900** [comment]
No this is on contact with a player, that one is for just if it despawns, or hits a wall

**Comment by EmeraldLoc** [comment]
Alright I understand. I did do this when I was adding the particle effect, so this is already done. For the future, if you made a similar issue on the subject, and you dont have access to the dev build its fixed on (which for that issue you do), then go ahead and make an issue like you did here, however if you do have access to the dev build that has this fixed on (which you do), you should verify that that has or hasn't been added yet first, since you have the resources to check.
