### ISSUE TITLE
Make the game not go into the waiting state immediately after a player spectates (in 2 - 3 players)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1423]
Instead, make it so that if a player is still spectating even the round countdown is over, then the round would go into the waiting, make nubs abusing it to get new levels a lot rarer, and would also preserve a useful trick that I and many others use.

**Comment by EmeraldLoc** [comment]
Huh?

**Comment by TheMan6900** [comment]
If you spectate and unspectate while a round is in the state of starting, the level will automatically change to a different level, this would prevent that by only putting the round into the waiting state if the start timer is at 0 and a player is still spectating (hope that made sense)

**Comment by EmeraldLoc** [comment]
The reason it changes levels is because the gamemode does not have a player limit under 3 players, and there are 3 players playing, so it kicks the players out of that game, then sends them into a new one. I take it you are asking to make the player stay in the same level, however what should really happen is the game should simply end and head to the leaderboards.
