### ISSUE TITLE
Hacker Anti-Cheat

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1505]
Not sure if this would be possible to implement but would definitely be nice, especially since I've seen tag get hacked like 4 times by now in servers that aren't my own. Just simply don't allow them (hackers) to mess with tag setting (also the round timers but I'm not sure if that's possible)

**Comment by EmeraldLoc** [comment]
So the hacker was affecting tag settings? Was this person doing anything else that could reliably deemed as hacks, or was he also doing that?

**Comment by TheMan6900** [comment]
He was both messing with tag settings and messing with the round timers (intermission, time remaining, etc), basically making them end instantly.

**Comment by EmeraldLoc** [comment]
Hmm, and thats all this hacker did?

So the issue here is that intermission, round countdowns, and voting timers are all handled via a local variable (one a client cannot see). Sure, you could change the synced timer var, but that will instantly reset back to the intended value. You can think of it as this internal variable is readable and writable to only the server, however what the client sees (the global timer) is only readable. So in order for this to really be a hacker, it would have to be done by the server, so is someone else hosting this mod, cause it could just be them trolling. Were you the host or someone else?

Also, hackers are very hard to come by, because it takes programming knowledge (or illegal distribution of a hacked client) to do so, not including making a hacked client that could inject its own code into the server's mod (which would be very dangerous, not just for tag here, but for the whole community as a whole), so it's very unlikely this was a hacker, which means it's either the host trolling, or a bug in Tag.

**Comment by TheMan6900** [comment]
It was just me hosting a server

**Comment by TheMan6900** [comment]
(also I should note that a popup saying "LOST CONNECTION TO SERVER" appeared)

**Comment by EmeraldLoc** [comment]
In all caps like that? Such a popup does not exist in vanilla coop, nor tag, so either its another mod you're using or a hacker goofing off with popups.

What other mods were you hosting with?

**Comment by TheMan6900** [comment]
Just the b3313 and megamix plugins

**Comment by EmeraldLoc** [comment]
Is this "hacker" still in the server?

**Comment by TheMan6900** [comment]
no I restarted it a long time ago

**Comment by EmeraldLoc** [comment]
Did you have someone in there set as a moderator when you did not intend that?

**Comment by TheMan6900** [comment]
nope

**Comment by EmeraldLoc** [comment]
While tag settings could have been a hacker, I do not believe it so that it was a hacker affecting the round intermission states, I can only assume it was a bug. Because 2.4.1 and 2.4 have vastly different code in many places now, it's hard to figure out if the error exists in 2.4.1 as well. I am going to close this and assume it as a "fluke" that is "fixed in 2.4.1 frfr"
