### ISSUE TITLE
New star road map - Colorful Coral Caverns (but as a sections map)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#205]
Like hmc, this level would be comprised of multiple section, like the pipe n' bombs area, the outside upper portion area, and the lowest portion area, etc.

**Comment by EmeraldLoc** [comment]
@PolarBear32 think you could do this?

**Comment by PolarBear32** [comment]
Hmm. Not too experienced with Star Road. I'm not sure if I'd want to necessarily put dedication into this map, since I don't really care enough about the Star Road tag port.

**Comment by EmeraldLoc** [comment]
Alr it's fine, I'll take a peek at it

**Comment by Bear64DX** [comment]
Looking back on this idea; I'm not sure if this map would work. Having more SR stages *can* be cool, but tbh, I don't think this map would work. Not only is it ABSURDLY big, but I *reaaally* don't think that making this a section map is the way to go. Only *certain* levels can be good when split. This level does not fall into that category of "certain levels that work being split". If I'd add this, it'd be one big map because I think that's the best option for this map. However, I'm still not sure how to make this map good, as it's worse than MMM (non remastered).

**Comment by TheMan6900** [comment]
Can I cook this level emerald?
