### ISSUE TITLE
New setting - Tag Camera

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#389]
Kinda like romhack cam, this would be a camera option that would make the camera more so built for tag, with the camera panning towards taggers/runners and also the backwards camera idea bear suggested.

**Comment by EmeraldLoc** [comment]
Oh man.......... sounds like a fun project for another day.

**Comment by TheMan6900** [comment]
FOR REAL !!

**Comment by TheMan6900** [comment]
(this would also apply to both freecam and analog cam, and also other camera settings if there are any that get added)

**Comment by TheMan6900** [comment]
oh alright.

**Comment by Bear64DX** [comment]
> > freecam and analog cam
> 
> These camera's are perfect, so there's no need to edit them.

you ain't wrong fella

**Comment by TheMan6900** [comment]
true

**Comment by Bear64DX** [comment]
I still feel like backwards cam w/ free cam would be cool, could be toggled with the L button

**Comment by TheMan6900** [comment]
The L button already has a function with freecam

**Comment by Bear64DX** [comment]
It just pans the camera, which is really, really useless

**Comment by Bear64DX** [comment]
Wait, fr? Nah I gotta see this

**Comment by Bear64DX** [comment]
WAIT THATS GOATED-

**Comment by TheMan6900** [comment]
yep

**Comment by TheMan6900** [comment]
Make a white outline of your character appear, when obscured but an object/terrain.
and two,
Make it that your character vanishes while your zooming on them.

**Comment by TheMan6900** [comment]
Oh yeah, make the camera general pan towards the direction your facing.

**Comment by EmeraldLoc** [comment]
> zoom out more than freecam can.

This funny thing is called an unfair advantage

**Comment by Bear64DX** [comment]
GS actually has this in the port :troll:

**Comment by EmeraldLoc** [comment]
I don't think I'm qualified to make this camera. I was making the camera for a good bit, and I just keep making it more and more like freecam, since I consider freecam the optimal camera choice. I don't play with vanilla cam a lot, and I don't know what makes that camera good (since to me it sucks). I just feel like freecam IS the perfect tag camera. I'm just simply unsure of how the camera should feel.

**Comment by Bear64DX** [comment]
freecam's goated, I mean a tag cam sounds cool but I honestly don't know how this can compete with Freecam

**Comment by TheMan6900** [comment]
I mean this could just be freecam with some nice qols

**Comment by TheMan6900** [comment]
or just be labeled "Camera Enhancements"

**Comment by EmeraldLoc** [comment]
> this could just be freecam with some nice qols

Freecam doesn't need "quality of life" changes. It's perfect. It can't be improved. It is as good as it can possibly be. There are no changes needed. It is untouchable. It's the goat. It's everything a good camera should be.

**Comment by TheMan6900** [comment]
true

**Comment by Bear64DX** [comment]
This issue has still been open so I'm just going to bump this real quick.
I think instead of there being "Tag Cam" it just turns into "Backwards Cam". It'd work with Freecam and you'd hold down L to do it. I think what Freecam does with the L button is useless. Sure it pans the camera to where you're facing, but I honestly can't imagine myself using that much. If it was replaced with Backwards Cam, where if you press the L button the camera pans backwards, I think that'd be a neat QOL. Freecam also works, but turning the R stick is too slow and messes with your controls. It's hard to run away while slowly panning Freecam to the back. With this concept, if you hold L down, it automatically pans the camera backwards to where you're facing. If you released L, the camera would go back to normal, and using Backwards Cam wouldn't mess with controls, unlike Freecam

**Comment by EmeraldLoc** [comment]
Sounds great for another mod, doesn’t really feel like a feature necessary for tag. Also the only reason this is still open is because I like the idea of a custom camera that gives you freedom and slowly pans to other players, but as a free cam user I can’t quite understand what makes a good “vanilla cam”

**Comment by Bear64DX** [comment]
Backwards cam is good enough imo. I'd code it in but idk how to.

**Comment by EmeraldLoc** [comment]
Probably gonna close this, just too clueless on what this should be
