### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#403]
Basically, it could be a minimap which could display other runners and hunters (hunters would be metal).
Eliminates wouldn't be shown.

**Comment by TheMan6900** [comment]
Sardines, Finished, And Spectating Players Wouldn't be showed either.

**Comment by EmeraldLoc** [comment]
I've never liked minimaps, not because of the minimaps themselves, but the implementation of the minimaps. There's no way to create a minimap dynamically, and I refuse to use the DS minimaps, so I don't think i'll add this. When a function exists to get the color of a surface, then I'll look into making this, for now it's a no.
