### ISSUE TITLE
Bind To Open Settings

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#5]
Make it so that you can open/close the menu with a button (could be bindable), along with this, make it so that the menu reopens where you left off on it before closing it.

**Comment by EmeraldLoc** [comment]
> make it so that the menu reopens where you left off on it before closing it

I will not be adding this, simply because I believe it's worse than what it is now. I will however be adding the bind to open settings

**Comment by Bear64DX** [comment]
> > Make it so that you can open/close the menu with a button
> 
> I was gonna do this (as you may have saw the unedited message), however it requires a good chunk of work rewriting the binds system, and in the end you can just pause, and hit tag settings, or type /tag, both end up being nearly just fast when you get used to either maneuver. If someone adds it, wont be against merging it though.

How would this require rewriting the binds system? It doesn't sound too complicated at least in my head (i mean tbf this message was posted on April 28, 2024 so its kinda outdated atp)

**Comment by EmeraldLoc** [comment]
Why, yes, it could of course be binded to a single button, however doing this would almost certainly cause mod compatibility issues. Instead, it would require a 2 button combo, which honestly would not be hard to add, it'd take like an hour (although I would have to figure out how to detect 2 buttons are down rather than one, which may be quite a challenge). This is why a new bind "rewrite" (pretty extreme word here, better described as "feature") would be required. It isn't really a priority, and I certainly won't add it, but if anyone else wants to give it a go with a proper implementation, I would not hesitate on merging it in.

**Comment by Bear64DX** [comment]
> Why, yes, it could of course be binded to a single button, however doing this would almost certainly cause mod compatibility issues. Instead, it would require a 2 button combo, which honestly would not be hard to add, it'd take like an hour (although I would have to figure out how to detect 2 buttons are down rather than one, which may be quite a challenge). This is why a new bind "rewrite" (pretty extreme word here, better described as "feature") would be required. It isn't really a priority, and I certainly won't add it, but if anyone else wants to give it a go with a proper implementation, I would not hesitate on merging it in.

So basically you'd need to rewrite or recode a new system allowing for button combos/multiple inputs, rather than just one input?
