### ISSUE TITLE
Search Teamwork

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#562]
Make it so that in search, when you tag someone, they become a seeker. (They just disappear and it looks weird. It's kinda just terminator tbh) This was in a 3P lobby so idk if that has smth to do w/ it

**Comment by EmeraldLoc** [comment]
> It's kinda just terminator tbh

Oh my, will you look at this, you figured it out!

The only real difference between the 2 is the lack of a radar and you being frozen in place as a hider (and the 30 sec you get), so hey, idek why this is here, I just added it cuz I keep getting bombarded with ppl wanting me to.

Anyways, the seeker making you caught makes the most sense to me, and otherwise the mod would just become Infection (The entire Hide and Seek mod, and all the ways it can be changed, are pretty much the Infection and Terminator gamemodes without the radar). Idk, maybe removing the gamemode would be a better idea, this gamemode could be entering a place I don't want to go, quantity over quality gamemodes.

**Comment by TheMan6900** [comment]
> Idk, maybe removing the gamemode would be a better idea, this gamemode could be entering a place I don't want to go, quantity over quality gamemodes.
 
You can't really just remove a gamemode, cause of stats and other savables

**Comment by EmeraldLoc** [comment]
> You can't really just remove a gamemode, cause of stats and other savables

I can. Search has not been released yet, there's nothing stopping me changing the gamemode out for another one or completely removing it. The decision to remove it is not final, I need to think about it a bit more.

**Comment by Bear64DX** [comment]
Quanity over Quality is never a good direction to go. I'd say we figure smth out for this gamemode or give it the boot.

**Comment by TheMan6900** [comment]
Search really isnt that bad though, imo it just needs to be fixed and revamped.

**Comment by Bear64DX** [comment]
What if search was removed and instead just made as an option for sardines that can let you decide how many hiders you want.

**Comment by TheMan6900** [comment]
> What if search was removed and instead just made as an option for sardines that can let you decide how many hiders you want.

Just use the player menu.

**Comment by Bear64DX** [comment]
I'm not sure if the host would want to manually make players sardines. Oh and an addendum to what I said above:
I feel like it'd be cool if you could also change the sardine hiders to "Auto", which will make certain players hiders depending on the server count. (MH has a system like this so I'm sure you can use that a base for a system like this.)

**Comment by TheMan6900** [comment]
> I'm not sure if the host would want to manually make players sardines. Oh and an addendum to what I said above: I feel like it'd be cool if you could also change the sardine hiders to "Auto", which will make certain players hiders depending on the server count. (MH has a system like this so I'm sure you can use that a base for a system like this.)

Still just kinda feels unnecessary

**Comment by Bear64DX** [comment]
Better than having some gamemode that's just a copy of another but slightly changed (quanity over quality)

**Comment by EmeraldLoc** [comment]
>  it just needs to be fixed and revamped

More description.

Here's what I'm leaning towards. Search is, I mean, REALLY, if not the same, as hide and seek. "Tag", the idea/concept/a word I made it, isn't really about hiding, it's about chasing other players and getting a bunch of dopamine from hitting a slidekick to preserve speed and get away from the taggers. Tag, Freeze Tag, Infection, Hot Potato, Juggernaut, Assassins, Hunt, Deathmatch, Terminator, and Oddball all accomplish this, Sardines and Search are just oddballs (pun intended) in what all the other gamemodes are. I'm beginning to doubt if I should have even added sardines into Tag, that may have been a mistake. I don't like the direction I was heading with Sardines and Search, and I think I should stay away from gamemodes like that. Since I have an opportunity to, I'm probably gonna end up scrapping Search. I would do the thing Bear suggested (multiple seekers in one gamemode, Sardines), however the stats wouldn't carry over well at all, it isn't reasonable. 

It's crazy what 5 minutes of thinking can do.

**Comment by Bear64DX** [comment]
I honestly wish there was an easy way to remove Gamemodes. It's just that stats make this hard to accomplish

**Comment by EmeraldLoc** [comment]
> I honestly wish there was an easy way to remove Gamemodes

When the merge to coopdx happens, there may be a way to do this very thing, however I would be worried about doing this.

If 2.4 is released, the index for the gamemode could be removed, and the stats could be removed for players only on coopdx. Great! Now, let's say 2.5 rolls around. That index has since been filled, the migration goes smoothly, wonderful, great so far! Now, the player has dumped 9 hours into that gamemode alone, they have over 120 runner wins, and say 50 tagger wins. Now, they join a 2.4 lobby because that's the most popular lobby. Boom, save is gone.

Idk who ppl hosted the mod with, however since Search was in a beta that was never hosted publicly, no stats should exist for 99.999% of players, so developers would be able to remove the stats from their save files. That's why I think removing Search is completely fine, since it shouldn't have been hosted with a lot of ppl, so ye.

**Comment by TheMan6900** [comment]
I feel like having gamemodes like sardine (or I guess search), really help freshin the pace of the game, and I personally think its better to keep gamemodes like them, though thats just my opinion.

**Comment by Bear64DX** [comment]
It turns "Tag" into "Hide and Seek", like what emerald said. Also I'm just wondering, how would this be easier with DX rather than EX?

**Comment by EmeraldLoc** [comment]
> I feel like having gamemodes like sardine (or I guess search), really help freshin the pace of the game, and I personally think its better to keep gamemodes like them, though thats just my opinion.

The problem with that is when you start doing that, Tag starts becoming the "every gamemode here" mod, and I don't want this mod to be that. I just want all the tag type gamemodes in one place, so ppl don't have to download a tag, freeze tag, infection, and hot potato mod when all of them are very similar.

**Comment by TheMan6900** [comment]
Hide and Seeks is fun though, but again just my opinion

**Comment by EmeraldLoc** [comment]
> how would this be easier with DX rather than EX?

`mod_storage_remove` is only on dx, not ex-coop.

**Comment by Bear64DX** [comment]
> Hide and Seeks is fun though, but again just my opinion

It's fun when the mod's actually BUILT for hide and seek, not tag.

**Comment by TheMan6900** [comment]
> It's fun when the mod's actually BUILT for hide and seek, not tag.

still, varies fun though

**Comment by Bear64DX** [comment]
If I'm playing tag, I want to be playing Tag.

**Comment by TheMan6900** [comment]
> If I'm playing tag, I want to be playing Tag.

you still do tag people in sardine/search though.

**Comment by TheMan6900** [comment]
just in a different way

**Comment by Bear64DX** [comment]
I guess but it's still NOT tag, it's basically an entirely new concept from tag. Just because you "hit someone", doesn't mean it's already associated w/ tag

**Comment by Bear64DX** [comment]
> just in a different way, kinda like literally every gamemode in this mod

In every gamemode, you're always running trying to hit someone. Sardines is the opposite, because you're trying to SEARCH for someone, not tag someone.

**Comment by EmeraldLoc** [comment]
> Hide and Seeks is fun though, but again just my opinion

So are a lot of things, mariohunt, kart battle modes, and hey, even mods that I made originally (Star Rush, etc.) could be considered fun. Just because of that though doesn't mean it should be in Tag. Hide and Seek should be a separate mod with it's own variants, not bounded by the engine of Tag.

Anyways, gonna close this now, the final decision is I'm going to be removing Search. Everyone's entitled to their own opinion, however I may not have your opinion, so some decisions I make may or may not favor your opinions. 

> you still do tag people in sardine/search though

Yea, I also tag the star to collect it. The activity isn't "chasing and running", it's "go find the hider!!!!".

**Comment by Bear64DX** [comment]
> The activity isn't "chasing and running", it's "go find the hider!!!!".

Exactly.
