### ISSUE TITLE
Tagger Speed

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#642]
Make taggers have a passive 1.03 speed boost (would help balance taggers)

**Comment by TheMan6900** [comment]
This should honestly be a thing in the game, id actually be a good way to balance taggers more.

**Comment by EmeraldLoc** [comment]
no, get good, or don't play on ridiculously large maps and play on maps where strategy can be invoked.

**Comment by TheMan6900** [comment]
brah, consider players that arent as good

**Comment by EmeraldLoc** [comment]
They can get good. I started off playing this game playing hide and seek, more like tag, and I sucked. I wasn't super bad, like I could long jump and try to hit a wall kick, but I wasn't good by any means. I kept playing hide and seek, freeze tag, infection, all while working on modding skills, speed running, playing romhacks, and I got good, and now I can speed kick, hit firsties on demand, and sightread levels. Mods shouldn't be nerfed to serve bad players, they should have a low skill floor and high skill ceiling for the best gameplay, Tag already has a low skill floor, however increasing tagger's speed lowers the skill ceiling and isn't good. That's why I don't really care if a player is bad at the game, and they want me to nerf something, because I believe that instead of wanting nerfs you should get better at the game and begin to use boosts appropriately and what not.

**Comment by TheMan6900** [comment]
Adding a passive 1.03 boost wont lower the skill ceiling that much, and will be funner for taggers.

**Comment by TheMan6900** [comment]
just because a mechanic lowers the skill ceiling of the game, doesnt make it bad, just makes it so that more people can have fun.

**Comment by EmeraldLoc** [comment]
I honestly don't really have anything to say except I just disagree with this. It's gonna be subjective, and I don't believe it's a good thing to add to the mod, so there it is. Use your boost, its there for a reason.
