### ISSUE TITLE
New api - OverrideBackdrop

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#897]
Would replace a levels backdrop with another

**Comment by EmeraldLoc** [comment]
whats a backdrop?

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/8403ab73-c350-414a-b01b-0c96448c5c38)

**Comment by EmeraldLoc** [comment]
Skybox? I don't know if a skybox should be replaced... why are you doing this?

**Comment by TheMan6900** [comment]
more specifically for bear's b3313, where a lot of levels have black skyboxes

**Comment by EmeraldLoc** [comment]
Well, if that's the way the dev intended it, I don't think it should be changed. If it's a bug with the level, it should be fixed on that level, and tag should not need to fix it.

**Comment by TheMan6900** [comment]
> Well, if that's the way the dev intended it, I don't think it should be changed. If it's a bug with the level, it should be fixed on that level, and tag should not need to fix it.

fair

**Comment by Bear64DX** [comment]
Lots of levels in the port don't have black skyboxes. And if they do, that's intended. I'll add a skybox if I want to add a skybox.
(Also sometimes i change the skyboxes on a level bc i sometimes think the skybox i added fits more w/ the level. For example, I changed Ice, Cold Crevasse's skybox to a winter one, rather than a black one bc I think it fits better. Sooo yeah)

**Comment by EmeraldLoc** [comment]
Well, thats the romhacks author choice, not Tag's.

**Comment by Bear64DX** [comment]
> Well, thats the romhacks author choice, not Tag's.

or the romhack porter's choice lol. But yeah, I agree
