### ISSUE TITLE
Make The Menu Open Control Scheme "Dpad Down", Into "Z + Dpad Down" When Playing With Tag 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#941]
![image](https://github.com/user-attachments/assets/d8838421-58fa-48eb-b50e-a3c506066ec6)
probably dont need to say why this is a problem (also omm does this so it is possible to do)

**Comment by Bear64DX** [comment]
Idk if this is that necessary tbh. Though CS has an API iirc so I think it's possible.

**Comment by EmeraldLoc** [comment]
What’s the problem? What mod does this occur in?

**Comment by Bear64DX** [comment]
> What’s the problem? What mod does this occur in?

It isn't necessarily a problem. TM wants the Character Select mod to scream at you when tag is enabled. Personally I don't see why this is needed because... why? I mean not everything needs an exclamation mark at the end of it but eh, his suggestion ig

(EDIT: idk the problem lol uhh, will prob delete this ig)

**Comment by EmeraldLoc** [comment]
What? TheMan can you please elaborate on this?

**Comment by TheMan6900** [comment]
the character select mod, just constantly conflicts with the tag mod's menu

**Comment by EmeraldLoc** [comment]
In what way's? Inputs should be disabled in the tag pause menu when CS is opened.

**Comment by EmeraldLoc** [comment]
Ah, I figured out what you mean, I can add a hook to prevent this, however I can't change core CS functionality.

**Comment by Bear64DX** [comment]
Nvm I had it wrong lol

**Comment by EmeraldLoc** [comment]
Resolved
