### ISSUE TITLE
Make voting actually random instead of just picking the leftmost option

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#944]
Exactly what it says in the title.

**Comment by EmeraldLoc** [comment]
No, and I'll explain why.

Levels are added to a table, the leftmost index being a index of 1, the rightmost (that's not random), being 3, middle 2. It adds levels from 1 to 3. What this means is that the index to the left is what would've been picked if voting was off. Because of that, I believe that level should have priority over others, same with middle and last.

Also yea call me a nerd if you want lol.
